<style type="text/css">@import url(/css/main.css);</style>
<!-- <div class="largeTitle">About No Restrictions Entertainment</div> -->

<div id="about-video">
	<iframe width="622" height="350" src="//www.youtube.com/embed/XrlXlrJNv5k" frameborder="0" allowfullscreen></iframe>
</div>

<p style="padding-top: 20px; text-align: center; clear: left;">No Restrictions Entertainment focuses on making feature films that deal with current social issues which entertain and have an emotional impact. The stories told come from people we have known or interviewed and contain a point of view about what we believe is true. Our goal in telling these stories is to show the complexities of an issue and at the same time, profile the incredible possibilities for human endurance, resilience, and hope. Our hope is that people will walk away with a greater understanding about the causes and effects of the issues, inspired to take action in their communities.</p>
 
<div class="section-divider dashed"></div>				
<table cellpadding="0" cellspacing="6">
	<tr>
		<td width="225"><img src="/images/about/edgar_michael_bravo_bio.jpg" class="border"/></td>
		<td>
			<div class="largeTitle" style="border: none; margin-bottom: 5px; padding-bottom: 5px;">Edgar Michael Bravo</div>
			<p>Latino writer/director Edgar Bravo has explored the residual effects of  the North American and Latino culture clash. During his studies at the UCLA  graduate school of film (MFA), Mr. Bravo's film &quot;Mi Casa&quot;,  which dealt with Latino immigrants in L.A., won the grand prize at the A&amp;E  national film competition. This prestigious&nbsp;<a href="http://www.imdb.com/search/name?bio=award">award</a>&nbsp;helped launch  his directorial career and Mr. Bravo took on his next challenge: &quot;Mi  Hermano&quot; which was the first drama to deal with the ramifications of AIDS  and Latino immigrants. This poignant, edgy film garnered Mr. Bravo a Cine Eagle&nbsp;<a href="http://www.imdb.com/search/name?bio=award">award</a>&nbsp;and was  broadcast nationally on Univision and PBS.<br /><br />

			After receiving his Masters of Fine Arts from UCLA  with honors, Mr. Bravo wrote and directed the feature&nbsp;<a href="http://www.imdb.com/title/tt0104471/">I'll  Love You Forever... Tonight</a>&nbsp;(1992), which won national rave reviews including the  L.A. &amp; N.Y. Times. The project co-starred Thomas Jane (Boogie Nights,  Magnolia, 61*, Dreamcatcher). Phaedra released the film nationally. Video  distribution was handled by BlockBuster and Hollywood Video. Lumiere Films  (producers of 'Leaving Las Vegas') saw I'll Love You Forever tonight and hired  him to complete&nbsp;<a href="http://www.imdb.com/title/tt0114831/">Venus Rising</a>&nbsp;(1995), a  feature that required a re-write and re-shoots. They were so pleased with Mr.  Bravo's take on the material, that they hired him to write the feature &quot;The  Perfect Husband&quot;. Mr. Bravo's film &quot;Mi Hermano&quot; was viewed by  Columbia-Tri-Star and Telemundo and led to his first directorial stint in  television. Mr. Bravo shot an hour-long episode of&nbsp;<a href="http://www.imdb.com/title/tt0233102/">&quot;Reyes  y Rey&quot;</a>&nbsp;(1998), a popular police drama based in a fictional  Latino border town. The episode received such high ratings that he was  contracted to direct two episodes of their other co-production  &quot;Angeles&quot;, a Latino version of 'Charlie's Angels.<br /><br />

			The&nbsp;<a href="http://www.imdb.com/search/name?bio=award">award</a>&nbsp;winning San Francisco writers Bob Vickery and Dale Chase  granted Mr. Bravo rights to their stories after they reviewed his body of work.  The result was the script &quot;Lust, Love &amp; Repetition&quot;, which is  currently in production with Mr. Bravo as director. Mr. Bravo's script  &quot;The Closing Bell&quot; has been selected by the Telluride Indie Fest as  one of the top 25 indie scripts of 2002. <br />
			In 2008, Mr. Bravo and then first time producer John Paul Rice partnered  to form No Restrictions Entertainment to produce the critically acclaimed indie  feature <a href="http://www.imdb.com/title/tt1199557/combined">One Hour Fantasy  Girl</a>, written and directed by Edgar. The following year, they teamed up  with Ten Thirty One Pictures to produce <a href="http://www.imdb.com/title/tt1578270/combined">The Magic Stone</a> and  returned as a duo for <a href="http://www.imdb.com/title/tt1728981/combined">Mother&rsquo;s  Red Dress</a>. All three films deal with challenging social issues while  telling an entertaining and original narrative story. Mr. Rice and Mr. Bravo  are currently preparing for their fourth feature in four years, Monster Killer,  a supernatural, psychological thriller to shoot in 2012.<br />

			Mr. Bravo's great dream is to direct his script, &quot;The Conquest Of  Mexico&quot;, which depicts the beauty of Mexico before the treachery of Cortez  and European diseases he brought devastated a highly developed indigenous culture.</p>
		</td>						
	</tr>
	<tr>
		<td width="225"><img src="/images/about/john_paul_rice_bio.jpg" class="border"/></td>
		<td>
			<div class="largeTitle" style="border: none; margin-bottom: 5px; padding-bottom: 5px;">John Paul Rice</div>
			<p>John Paul Rice was born the youngest of four children, in Ft.  Lauderdale, Florida in 1978. His family moved to Alpharetta, Georgia (just  north of Atlanta) and built a home there in 1980. After his parents' divorce,  his mother moved him to Louisville, Kentucky where he began performing theatre  at the age of 7. The summer following his sophomore year of high school, John  moved back to Atlanta where he finished high school and attended Georgia State  University to pursue a degree in Business. In 1999, while at college, Rice was  given a rare opportunity to work on Jerry Bruckheimer's&nbsp;<a href="http://www.imdb.com/title/tt0210945/">Remember  the Titans</a>&nbsp;(2000).  Following three months on the film, John directed his studies toward learning  the history of cinema. He gained hands-on production experience by working on a  handful of micro-budget independent films between courses before moving to Los  Angeles January 2001 to pursue a career in film production.<br /><br />

			By mid-2001, John landed a position at the Los  Angeles division of the German distribution company Senator International  (which later became Mandate Pictures) led by industry veteran&nbsp;<a href="http://www.imdb.com/name/nm0236944/">Joseph  Drake</a>. Under Joe's mentoring, John developed an interest and  dedication to producing feature films. In 2008, Mr. Rice formed No Restrictions  Entertainment LLC with filmmaker&nbsp;<a href="http://www.imdb.com/name/nm0106068/">Edgar Michael Bravo</a>.<br /><br />
			
			The duo has produced three films together. The critically acclaimed  indie feature <a href="http://www.imdb.com/title/tt1199557/combined">One Hour  Fantasy Girl</a>, written and directed by Mr. Bravo. The following year, they  teamed up with Ten Thirty One Pictures to produce <a href="http://www.imdb.com/title/tt1578270/combined">The Magic Stone</a> and  returned as a duo for <a href="http://www.imdb.com/title/tt1728981/combined">Mother&rsquo;s  Red Dress</a>. All three films deal with challenging social issues while  telling an entertaining and original narrative story. Mr. Rice and Mr. Bravo  are currently preparing for their fourth feature in four years, Monster Killer,  a supernatural, psychological thriller to shoot in 2012.</p>
		</td>						
	</tr>									
</table>