<!-- <div class="largeTitle">The Film</div> -->
<!-- <div class="section-divider white" style="margin-bottom: 30px;"></div>				 -->
<img id="filmPoster" src="/films/one-hour-fantasy-girl/images/poster.jpg" class="border"/>
<div id="filmDesc">
	<h2 class="headline subheadline caps">Synopsis</h2>						
	<p>Based on a true story, ONE HOUR FANTASY GIRL is a compelling coming-of-age drama that is like no other film of its kind. Boldly honest and  thought provoking, the film introduces audiences to the world of a  twenty-year-old fantasy girl: Becky Lewis (Kelly-Ann Tursi), who escaped an  abusive alcoholic mother at the age of 15 and has been surviving on her own in  Los Angeles ever since.<br /><br /> 
	Having always struggled for money, Becky becomes business partners with Chi Trang (Paul D.  Nguyen), an aspiring musician, who convinces her to work as a fantasy girl,  acting out any fantasy a guy wants as long as there is no sex, no nudity and is  100% legal. She immediately gains two frequent customers, Roger (Jon Morgan  Woodward) and Bobby (Joe Luckay), who change her life forever.<br /><br />
	Becky finds herself in a web of deceit, betrayal  and murder that forces her to give up her own happiness. Shaken and bruised,  yet determined to make it, Becky pushes forward hoping to earn enough money to  invest in real estate and make the &ldquo;big bucks.&rdquo; Her journey leads her to find  an unlikely ally who, for a moment, gives her the break she&rsquo;s never had.</p>					
	<div class="section-divider dashed"></div>	
	<h2 class="headline subheadline caps">Director's Statement</h2>
	<p>This film gave me the chance to tell a story of how our upbringing influences our actions and most of the time we are unaware of this as we stumble forward in our lives. Sometimes the only moments we honestly express ourselves is in our fantasies. The film is based on interviews with young women who work as &quot;One Hour Fantasy Girls&quot; in Los Angeles and their clients who find an outlet for their fantasies.</p>				
	<p>Casting is what I enjoy the most and is the most difficult. I look for actors who have an essence of the characters that they are to portray. I bring together the final choices for the roles and encourage improv sessions and this when I find the sparks that help me complete my casting decisions.</p>
	<p>The essence of my protagonist then influences how I design the production design and the scene compositions. In this film my protagonist feels torn between a realistic cold practical world and the warm dreams of how she wishes it to be. As result I split the film between very dreamy images full with rich colors and realistic images that are colder and less extravagant.</p>
	<p>On the set, after I have shot all the written dialogue, I make sure I have allotted enough time for the actors to improvise the essence of the scene.</p>
	<p>Besides, the editing, the next most difficult decision is the music. Again, I return to the inner world of my protagonist to find a score that can express that world.</p>							
</div>